

services:
  hmpps-template-kotlin:
    ports:
      - "8080:8080"

  hmpps-auth:
    ports:
      - "9090:8080"

  wiremock:
    ports:
      - "9091:8080"

  ui:
    build:
      context: ..
      dockerfile: Dockerfile
      target: production
      args:
        BUILD_NUMBER: "1.0.0"
        GIT_REF: "a1b2c3"
        GIT_BRANCH: main
    command: npm run start
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      ENVIRONMENT_NAME: dev
