# `docker-compose.remote.yml` is used to spin up a local deployment that
# connects to HMPPS dev environment rather than running each required service locally.
# It relies on a .env file to provide credentials/secrets for these remote services.
# URLs configured here point will point the dev environment.

services:
  hmpps-template-typescript:
    environment:
      AUTH_CODE_CLIENT_ID: ${AUTH_CODE_CLIENT_ID}
      AUTH_CODE_CLIENT_SECRET: ${AUTH_CODE_CLIENT_SECRET}
      CLIENT_CREDS_CLIENT_ID: ${CLIENT_CREDS_CLIENT_ID}
      CLIENT_CREDS_CLIENT_SECRET: ${CLIENT_CREDS_CLIENT_SECRET}
      HMPPS_AUTH_URL: ${HMPPS_AUTH_URL}
      TOKEN_VERIFICATION_API_URL: ${TOKEN_VERIFICATION_API_URL}
