# `docker-compose.local.yml` defines services that must be run locally
# to support a fully self-contained local development environment.
# Unlike `docker-compose.remote.yml`, no shared or remote infrastructure is used.

services:
  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    container_name: hmpps-auth
    ports:
      - "9090:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/auth/health" ]
    environment:
      SPRING_PROFILES_ACTIVE: dev
      APPLICATION_AUTHENTICATION_UI_ALLOWLIST: 0.0.0.0/0

  hmpps-template-typescript:
    depends_on:
      - hmpps-auth
