# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: quay.io/hmpps/hmpps-template-typescript
  tag: latest
  pullPolicy: IfNotPresent
  port: 3000

ingress:
  enabled: true
  enable_whitelist: false
  host: hmpps-template-typescript-dev.hmpps.service.justice.gov.uk
  cert_secret: hmpps-template-typescript-cert
  path: /

env:
  HMPPS_AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
  TOKEN_VERIFICATION_API_URL: https://token-verification-api-dev.prison.service.justice.gov.uk
  TOKEN_VERIFICATION_ENABLED: true