# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: quay.io/hmpps/hmpps-template-typescript
  tag: latest
  pullPolicy: IfNotPresent
  port: 3000

ingress:
  enabled: true
  enable_whitelist: false
  host: hmpps-template-typescript-dev.prison.service.justice.gov.uk
  cert_secret: hmpps-template-typescript-cert
  path: /

env:
  API_ENDPOINT_URL: https://api-dev.prison.service.justice.gov.uk/
  OAUTH_ENDPOINT_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth/
  NN_ENDPOINT_URL: https://digital-dev.prison.service.justice.gov.uk/
  API_WHEREABOUTS_ENDPOINT_URL: https://whereabouts-api-dev.service.justice.gov.uk/
  HMPPS_COOKIE_NAME: hmpps-session-dev
  REMOTE_AUTH_STRATEGY: "true"
  WEB_SESSION_TIMEOUT_IN_MINUTES: "60"
  VIDEO_LINK_ENABLED_FOR: "WWI"
  TOKENVERIFICATION_API_URL: https://token-verification-api-dev.prison.service.justice.gov.uk
  TOKENVERIFICATION_API_ENABLED: true
  REDIS_ENABLED: true
  SUPPORT_URL: https://support-dev.hmpps.service.justice.gov.uk/
